### ISSUE TITLE
[Bug] Accessing an already closed DB object

### ISSUE THREAD

**Issue by arkaic** [arkaic/CalNMacs#12]
04-08 11:53:09.331 28743-28743/org.arkaic.calnmacs E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: org.arkaic.calnmacs, PID: 28743
                                                                     java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteQuery: SELECT \* from foods;
                                                                         at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
                                                                         at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:58)
                                                                         at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:151)
                                                                         at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:123)
                                                                         at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:236)
                                                                         at android.widget.CursorAdapter.getItemId(CursorAdapter.java:258)
                                                                         at android.widget.AbsListView$RecycleBin.retrieveFromScrap(AbsListView.java:6868)
                                                                         at android.widget.AbsListView$RecycleBin.getScrapView(AbsListView.java:6598)
                                                                         at android.widget.AbsListView.obtainView(AbsListView.java:2345)
                                                                         at android.widget.ListView.measureHeightOfChildren(ListView.java:1281)
                                                                         at android.widget.ListView.onMeasure(ListView.java:1188)
                                                                         at android.view.View.measure(View.java:18796)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                         at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:664)
                                                                         at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:731)
                                                                         at android.view.View.measure(View.java:18796)
                                                                         at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1560)
                                                                         at android.view.View.measure(View.java:18796)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                         at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                         at android.view.View.measure(View.java:18796)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
                                                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
                                                                         at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                         at android.view.View.measure(View.java:18796)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                         at android.view.View.measure(View.java:18796)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                         at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
                                                                         at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
                                                                         at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                         at android.view.View.measure(View.java:18796)
                                                                         at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                         at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                         at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                         at android.view.View.measure(View.java:18796)
                                                                         at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
                                                                         at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by arkaic** [comment]
Fixed by moving cursor closing further along fragment lifecycle.
